from django.views.generic import TemplateView

class LoginView(TemplateView):
    ...

class SignUpView(TemplateView):
    ...

class PortfolioView(TemplateView):
    ...

class CVView(TemplateView):
    ...
