# Generated by Django 4.1.4 on 2022-12-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("occupation", models.CharField(max_length=32)),
                ("website", models.URLField()),
                ("phone", models.CharField(max_length=32)),
                ("location", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("degree", models.CharField(max_length=16)),
                ("freelance", models.BooleanField(default=True)),
            ],
        ),
    ]
