# Generated by Django 4.1.4 on 2022-12-12 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_resumeitem_alter_profile_degree"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "resumeitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portfolio.resumeitem",
                    ),
                ),
            ],
            bases=("portfolio.resumeitem",),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "resumeitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portfolio.resumeitem",
                    ),
                ),
            ],
            bases=("portfolio.resumeitem",),
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "resumeitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="portfolio.resumeitem",
                    ),
                ),
            ],
            bases=("portfolio.resumeitem",),
        ),
        migrations.RemoveField(
            model_name="resumeitem",
            name="description",
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.resumeitem",
                    ),
                ),
            ],
        ),
    ]
