# Generated by Django 4.1.4 on 2022-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_education_experience_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="text",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
